from __future__ import annotations

from typing import Any, Protocol

from ..ports import MaxClientPort


class MaxBackend(Protocol):
    """Internal backend contract for MAX library implementations."""

    def create_client(self) -> MaxClientPort: ...
    def make_file_attachment(self, path: str) -> Any: ...
    def make_photo_attachment(self, path: str) -> Any: ...
    def make_video_attachment(self, path: str) -> Any: ...
    def make_message_from_dict(self, payload: dict[str, Any]) -> Any: ...
    def opcode(self, name: str, default: int | None = None) -> Any: ...
    def opcode_value(self, name: str, default: int) -> int: ...
    def opcode_name(self, value: object) -> str | None: ...
    def fetch_history_payload(
        self,
        *,
        chat_id: int,
        from_time: int,
        forward: int,
        backward: int,
    ) -> dict[str, Any]: ...
    def get_video_payload(
        self, *, chat_id: int, message_id: int, video_id: int
    ) -> dict[str, Any]: ...
